version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk-8
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/projectrequirement'