version: 0.1

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
            - java -version
            - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/projectrequirementportall
  discard-paths: no