version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - build/target/*.jar
  base-directory: 'target/projectrequirement'